//! Chat Model Definitions
//!
//! This module contains the core data structures for representing chat messages
//! and conversation participants. It defines the fundamental types used throughout
//! the chat interface components.

/// Represents the role of a participant in the conversation
///
/// Two roles are supported:
/// - `Assistant`: Messages from the AI assistant
/// - `User`: Messages from the human user
#[derive(PartialEq, Debug, Clone)]
pub enum ChatRole {
    /// Represents messages generated by the AI assistant
    Assistant,
    /// Represents messages sent by the human user
    User,
}

/// Represents an individual message in the chat
///
/// Each message contains:
/// - The role of the sender (Assistant or User)
/// - The content of the message as a string
///
/// The content string may contain markdown formatting which gets rendered
/// by the Message component.
#[derive(PartialEq, Debug, Clone)]
pub struct ChatMessage {
    /// The role of the message sender (Assistant or User)
    pub(crate) role: ChatRole,
    /// The content of the message, may contain markdown
    pub(crate) content: String,
}
